name: batchdownloader
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  html: ^0.15.0
  path_provider: ^2.0.12
  permission_handler: ^11.3.1
  file_picker: ^8.1.2
  ffmpeg_kit_flutter: ^6.0.3  # Replace flutter_ffmpeg with this
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  sqflite: ^2.4.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
